// dashboard/src/views/Strategies.vue
<script setup>
import { inject, computed } from 'vue'

const { indices, config } = inject('dashboardState')

const riskParameters = computed(() => {
  const r = config.value?.risk || {}
  const m = config.value?.market_session || {}

  // Trailing is ACTIVE only if global enabled AND session allows it
  const trailingStatus = (r.trailing?.enabled && m.config?.allow_trailing !== false) ? 'ACTIVE' : 'OFF'

  return [
    {
      label: 'Profit Floor',
      value: r.profit_floor?.enabled ? `${r.profit_floor.lock_pct}%` : 'OFF'
    },
    { label: 'Trailing', value: trailingStatus }
  ]
})

const signalFilters = computed(() => {
  const s = config.value?.signals || {}
  const t = config.value?.trading_time_restrictions || {}
  const m = config.value?.market_session || {}

  return [
    { label: 'ADX Filter', value: s.enable_adx_filter ? `MIN ${s.adx_min_strength || 15}` : 'OFF' },
    { label: 'Direction Gate', value: s.enable_direction_gate ? 'ACTIVE' : 'OFF' },
    { label: 'Runners', value: m.config?.allow_runners ? 'ALLOWED' : 'OFF' },
    { label: 'Session Blackout', value: t.enabled ? t.avoid_periods?.[0] || '10:00-12:30' : 'OFF' }
  ]
})

const indicesList = computed(() => {
  if (Array.isArray(indices.value)) return indices.value
  return Object.values(indices.value).filter(i => i && i.key)
})
</script>

<template>
  <div class="space-y-6">
    <div class="flex items-center justify-between mb-2 px-2">
      <h2 class="text-sm font-black text-white uppercase tracking-widest flex items-center gap-2">
        <span class="w-2 h-2 rounded-full bg-primary-500"></span>
        Active Strategies
      </h2>
      <span class="text-[10px] font-bold text-gray-500 uppercase tracking-tighter">Live Config</span>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div v-for="idx in indicesList" :key="idx.key" class="glass glass-hover p-6 rounded-2xl flex flex-col gap-4 group overflow-hidden relative min-h-[160px]">
        <div class="absolute top-0 right-0 w-32 h-32 bg-primary-500/5 blur-3xl group-hover:bg-primary-500/10 transition-colors"></div>

        <div class="flex items-center justify-between relative z-10">
          <div class="flex flex-col">
            <span class="text-xl font-black text-white tracking-tight">{{ idx.key }}</span>
            <span class="text-xs font-bold text-gray-500 uppercase tracking-widest mt-0.5">{{ idx.timeframe }} Interval</span>
          </div>
          <div class="px-3 py-1 rounded-full bg-primary-500/10 border border-primary-500/20">
            <span class="text-xs font-black text-primary-400 uppercase tracking-tighter">{{ idx.strategy }}</span>
          </div>
        </div>

        <div class="flex flex-col gap-2 mt-auto relative z-10">
          <div class="flex items-center justify-between text-[10px] font-bold uppercase tracking-widest text-gray-600">
            <span>Status</span>
            <span class="text-emerald-500">Scoping Index</span>
          </div>
          <div class="w-full bg-white/5 h-1 rounded-full overflow-hidden">
            <div class="bg-primary-500 h-full w-2/3 animate-pulse"></div>
          </div>
        </div>
      </div>
    </div>

    <!-- Strategy Description Card -->
    <div class="glass p-8 rounded-3xl mt-8">
      <h3 class="text-lg font-black text-white uppercase tracking-widest mb-4">Implementation Logic</h3>
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div class="space-y-6">
          <p class="text-xs text-gray-400 leading-relaxed font-medium">
            The execution engine utilizes a multi-layered validation system. Primary entries are dictated by Supertrend flips on the 1-minute interval, while ADX strength scores and 5-minute HTF alignment act as critical gateways.
          </p>
          <div class="flex flex-wrap gap-4">
            <div class="px-4 py-2 rounded-xl bg-white/5 border border-white/10">
              <span class="block text-[10px] font-black text-gray-600 uppercase mb-1">Entry Strategy</span>
              <span class="text-xs font-bold text-white uppercase">Supertrend Trend</span>
            </div>
            <div class="px-4 py-2 rounded-xl bg-white/5 border border-white/10">
              <span class="block text-[10px] font-black text-gray-600 uppercase mb-1">Exit Engine</span>
              <span class="text-xs font-bold text-white uppercase">Dynamic ATR + SL</span>
            </div>
          </div>
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div class="bg-white/5 rounded-2xl p-6 border border-white/10">
            <h4 class="text-[10px] font-black text-gray-500 uppercase tracking-widest mb-4">Risk Parameters</h4>
            <div class="flex flex-col gap-3">
              <div v-for="param in riskParameters" :key="param.label" class="flex items-center justify-between">
                <span class="text-[11px] font-bold text-gray-400">{{ param.label }}</span>
                <span class="text-[10px] font-black text-white uppercase tracking-tighter">{{ param.value }}</span>
              </div>
            </div>
          </div>

          <div class="bg-white/5 rounded-2xl p-6 border border-white/10">
            <h4 class="text-[10px] font-black text-gray-500 uppercase tracking-widest mb-4">Signal Filters</h4>
            <div class="flex flex-col gap-3">
              <div v-for="filter in signalFilters" :key="filter.label" class="flex items-center justify-between">
                <span class="text-[11px] font-bold text-gray-400">{{ filter.label }}</span>
                <span class="text-[10px] font-black text-white uppercase tracking-tighter">{{ filter.value }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// dashboard/src/views/Strategies.jsx
import { createMemo } from 'solid-js'
import { For } from 'solid-js'
import { useDashboardContext } from '../context/DashboardContext'

export default function Strategies() {
  const { indices, config } = useDashboardContext()

  const riskParameters = createMemo(() => {
    const r = config()?.risk || {}
    const m = config()?.market_session || {}
    const trailingStatus = (r.trailing?.enabled && m.config?.allow_trailing !== false) ? 'ACTIVE' : 'OFF'
    return [
      { label: 'Profit Floor', value: r.profit_floor?.enabled ? `${r.profit_floor.lock_pct}%` : 'OFF' },
      { label: 'Trailing', value: trailingStatus }
    ]
  })

  const signalFilters = createMemo(() => {
    const s = config()?.signals || {}
    const t = config()?.trading_time_restrictions || {}
    const m = config()?.market_session || {}
    return [
      { label: 'ADX Filter', value: s.enable_adx_filter ? `MIN ${s.adx_min_strength || 15}` : 'OFF' },
      { label: 'Direction Gate', value: s.enable_direction_gate ? 'ACTIVE' : 'OFF' },
      { label: 'Runners', value: m.config?.allow_runners ? 'ALLOWED' : 'OFF' },
      { label: 'Session Blackout', value: t.enabled ? t.avoid_periods?.[0] || '10:00-12:30' : 'OFF' }
    ]
  })

  const indicesList = createMemo(() => {
    const val = indices()
    if (Array.isArray(val)) return val
    return Object.values(val).filter(i => i && i.key)
  })

  return (
    <div class="space-y-6">
      <div class="flex items-center justify-between mb-2 px-2">
        <h2 class="text-sm font-black text-white uppercase tracking-widest flex items-center gap-2">
          <span class="w-2 h-2 rounded-full bg-primary-500"></span>
          Active Strategies
        </h2>
        <span class="text-[10px] font-bold text-gray-500 uppercase tracking-tighter">Live Config</span>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <For each={indicesList()}>
          {(idx) => (
            <div class="glass glass-hover p-6 rounded-2xl flex flex-col gap-4 group overflow-hidden relative min-h-[160px]">
              <div class="absolute top-0 right-0 w-32 h-32 bg-primary-500/5 blur-3xl group-hover:bg-primary-500/10 transition-colors"></div>
              <div class="flex items-center justify-between relative z-10">
                <div class="flex flex-col">
                  <span class="text-xl font-black text-white tracking-tight">{idx.key}</span>
                  <span class="text-xs font-bold text-gray-500 uppercase tracking-widest mt-0.5">{idx.timeframe} Interval</span>
                </div>
                <div class="px-3 py-1 rounded-full bg-primary-500/10 border border-primary-500/20">
                  <span class="text-xs font-black text-primary-400 uppercase tracking-tighter">{idx.strategy}</span>
                </div>
              </div>
              <div class="flex flex-col gap-2 mt-auto relative z-10">
                <div class="flex items-center justify-between text-[10px] font-bold uppercase tracking-widest text-gray-600">
                  <span>Status</span>
                  <span class="text-emerald-500">Scoping Index</span>
                </div>
                <div class="w-full bg-white/5 h-1 rounded-full overflow-hidden">
                  <div class="bg-primary-500 h-full w-2/3 animate-pulse"></div>
                </div>
              </div>
            </div>
          )}
        </For>
      </div>

      <div class="glass p-8 rounded-3xl mt-8">
        <h3 class="text-lg font-black text-white uppercase tracking-widest mb-4">Implementation Logic</h3>
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <div class="space-y-6">
            <p class="text-xs text-gray-400 leading-relaxed font-medium">
              The execution engine utilizes a multi-layered validation system. Primary entries are dictated by Supertrend flips on the 1-minute interval, while ADX strength scores and 5-minute HTF alignment act as critical gateways.
            </p>
            <div class="flex flex-wrap gap-4">
              <div class="px-4 py-2 rounded-xl bg-white/5 border border-white/10">
                <span class="block text-[10px] font-black text-gray-600 uppercase mb-1">Entry Strategy</span>
                <span class="text-xs font-bold text-white uppercase">Supertrend Trend</span>
              </div>
              <div class="px-4 py-2 rounded-xl bg-white/5 border border-white/10">
                <span class="block text-[10px] font-black text-gray-600 uppercase mb-1">Exit Engine</span>
                <span class="text-xs font-bold text-white uppercase">Dynamic ATR + SL</span>
              </div>
            </div>
          </div>

          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div class="bg-white/5 rounded-2xl p-6 border border-white/10">
              <h4 class="text-[10px] font-black text-gray-500 uppercase tracking-widest mb-4">Risk Parameters</h4>
              <div class="flex flex-col gap-3">
                <For each={riskParameters()}>
                  {(param) => (
                    <div class="flex items-center justify-between">
                      <span class="text-[11px] font-bold text-gray-400">{param.label}</span>
                      <span class="text-[10px] font-black text-white uppercase tracking-tighter">{param.value}</span>
                    </div>
                  )}
                </For>
              </div>
            </div>

            <div class="bg-white/5 rounded-2xl p-6 border border-white/10">
              <h4 class="text-[10px] font-black text-gray-500 uppercase tracking-widest mb-4">Signal Filters</h4>
              <div class="flex flex-col gap-3">
                <For each={signalFilters()}>
                  {(filter) => (
                    <div class="flex items-center justify-between">
                      <span class="text-[11px] font-bold text-gray-400">{filter.label}</span>
                      <span class="text-[10px] font-black text-white uppercase tracking-tighter">{filter.value}</span>
                    </div>
                  )}
                </For>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
